server:
    port: 9999
spring:
  devtools:
    livereload:
      enabled: true

  application:
    name: spring-boot-teste
  boot:
    admin:
      client:
        url: http://192.168.100.70:8080
#  freemarker:
#    cache: false

#System.setProperty("spring:devtools:restart:enabled", "false");
#System.setProperty("spring:devtools:livereload:enabled", "true");


#redis:
#  server:


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

